[package]
name = "gallerust"
version = "0.1.0"
edition = "2024"

[dependencies]
eframe = "0.27"
egui = "0.27"
egui_extras = "0.27"
image = { version = "0.25", features = ["jpeg", "png", "gif", "webp", "bmp"] }
rfd = "0.14"

[[bin]]
name = "gallerust"
path = "src/main.rs"